### ISSUE TITLE
Unable to establish connection over UPURS 

### ISSUE THREAD

**Issue by ulften** [tom-seddon/beeblink#164]
Hi,
I have a working UPURS cable for my BBC B, verified with UPURS and HostFS towards a Linux box. I was eager to try beebLink, but must admit that I am unable to get past the sync stage. Since I was uncertain if my build on Linux worked properly, I tried two prepackaged builds for macOS. The results seem to be the same:

When the BBC boots, it prints out the name of the UPURS fe60 rom and beeps continuously, (pressing break again silences the beeping), but the BBC does not boot. It seems to be stuck in a loop trying to get past the initial sync.

Not sure what the best way to start up the server is, but this seems to be one way:
ulf@Ulfs-iMac beebLink % ./beeblink-server --verbose --serial-verbose --pc volumes/beeblink volumes
libusb_debug_level: ``null''
cwd: ``/Users/ulf/projects/beebLink''
save_config: ``null''
Search folders: 
BeebLink: 0. volumes 
TubeHost: None
PC: 0. volumes/beeblink 
Looking in: volumes...
    Looking in: volumes/beeblink_tubehost_tests...
        Looking in: volumes/beeblink_tubehost_tests/0.default...
SERIAL-DEVICES: /dev/tty.usbserial-AR0JQCCZ: new serial port
Note: using 1 auto-detected serial devices.
Note: to control which devices get opened, see --verbose --help output for these options: --serial-exclude, --serial-exclude-all, --serial-include 
/dev/tty.usbserial-AR0JQCCZ: setting FTDI latency timer to 1ms.
/dev/tty.usbserial-AR0JQCCZ: Setting USB device configuration...
/dev/tty.usbserial-AR0JQCCZ: Claiming USB device interface...
/dev/tty.usbserial-AR0JQCCZ: Ignoring claimInterface error: Error: LIBUSB_ERROR_ACCESS
/dev/tty.usbserial-AR0JQCCZ: Setting latency timer...
/dev/tty.usbserial-AR0JQCCZ: Done... hopefully.
/dev/tty.usbserial-AR0JQCCZ: serving. (verbose=true, data-verbose=(in: false, out: false), sync-verbose=false)
/dev/tty.usbserial-AR0JQCCZ: Waiting for request...
...
/dev/tty.usbserial-AR0JQCCZ: sync: write server step 2 sync data
/dev/tty.usbserial-AR0JQCCZ: No sync - bad sync value: 128 (0x80)
/dev/tty.usbserial-AR0JQCCZ: Sync: flushing buffers...
/dev/tty.usbserial-AR0JQCCZ: Sync: Waiting for 300 sync 0x00 bytes...
/dev/tty.usbserial-AR0JQCCZ: Received 300 0 sync bytes.
/dev/tty.usbserial-AR0JQCCZ: sync: write server step 2 sync data
/dev/tty.usbserial-AR0JQCCZ: No sync - bad sync value: 128 (0x80)
/dev/tty.usbserial-AR0JQCCZ: Sync: flushing buffers...
/dev/tty.usbserial-AR0JQCCZ: Sync: Waiting for 300 sync 0x00 bytes...
/dev/tty.usbserial-AR0JQCCZ: Received 300 0 sync bytes.
/dev/tty.usbserial-AR0JQCCZ: sync: write server step 2 sync data
...

I am pretty sure this is all on my side, but could use some help. I have three environments going that I can use:
Linux ubuntu 22.04 on a Intel NUC, MacBook Air M2 running Sonoma, and an old iMac  running Catalina, although I would prefer  getting this running on Linux.

While creating this message, I see an (ignored) error claiming the serial port - see above. Here is the device:
 0 crw-rw-rw-  1 root  wheel   18,   2 13 Dec 17:11 /dev/tty.usbserial-AR0JQCCZ

Any pointers to what to do next?
Thanks!
Ulf

**Comment by ulften** [comment]
Ok, my bad - wrong node version! With that corrected, the BBC is happier and the server starts up with npm start. Still not down, as I can't see the volumes or pass arguments to beeblink, but definitely a step forward. Sorry for the bother!

**Comment by tom-seddon** [comment]
Ah, excellent - thank you for the note. I have to admit that UPURS BeebLink doesn't get regular testing, but it is supposed to work!

Regarding command line options, make sure you are using `--` to separate `npm start` from the options, so that the options don't get consumed by npm: e.g., `npm start -- --help`.

To specify the folder(s) where volumes can be found, supply their paths on the command line, e.g., `npm start -- ./volumes`. It should find at least a volume called `beeblink`, containing the BeebLink tools, which you can access from the BBC using `*VOL BEEBLINK`. There's a mini walkthrough here: https://github.com/tom-seddon/beeblink/blob/wip/tom/docs/fs.md

Let me know if you have any difficulties and I'll try to help.

**Comment by tom-seddon** [comment]
BTW, regarding the BBC getting stuck, it might be possible the ROM will just sit in an infinite loop if it's receiving data but not getting to the end of the sync process. I can't remember. I've opened an issue about this: https://github.com/tom-seddon/beeblink/issues/165

**Comment by ulften** [comment]
Hi Tom,
My bad, but better late than never: Thank You for your additional information and an excellent repository! I did eventually figure it out and this is now my file system of choice for my BBC Micro.
/Ulf

**Comment by tom-seddon** [comment]
Thanks for letting me know, and I'm glad you're finding BeebLink useful! It's the main filing system on my BBCs too. I find the convenient PC interop super useful in both directions.

**Comment by tom-seddon** [comment]
BTW, since you mentioned you've got modern Macs as well: I did a bit of UPURS testing a few months ago, after getting an Apple Silicon Mac, and it looks like the serial port handling on modern macOS isn't currently UPURS-friendly. The issue for tracking this is here: https://github.com/tom-seddon/beeblink/issues/79 - looks like you could get lucky with Catalina if you install the older FTDI VCPI drivers?

I'm currently using Sequoia. I suppose it's possible that this is fixed in Tahoe.

I haven't figured out what to do about this yet, but I've got some ideas.
